Algoritmo "Aula 9 "
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/06/2020
Var
   cont , N : INTEIRO
   // Seção de Declarações das variáveis


Inicio
   cont <- 1
   Enquanto ( cont <= 10) faca
      Escreva ("Digite um valor: ")
      Leia (N)
      cont<- cont +1
      EscrevaL ()
   Fimenquanto
   // Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo