Algoritmo "imparOuPar"

Var

N: Inteiro
 C: caractere

Inicio
Enquanto (c= s)
      Escreva ("Digite um numero qualquer: ")
      Leia (N)
      Se (N % 2 = 0) entao
         EscrevaL ("o numero ", n, " é par")
      Senao
         EscrevaL ("O numero ", n," é impar")
      Fimse
Escreva ("Continuar S/N ?")
Leia (C)
     Se (C = s) entao
     senao
     Escreva L ("Tenha um bom dia! ")
fimse



Fimalgoritmo