Algoritmo "eIssoAeEuCopioCodigo"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/06/2020
Var
calista1, calista2: inteiro
// Seção de Declarações das variáveis 


Inicio
  Para calista1 <- 1 ate 3 faca
    Para calista2 <-   1 ate 3 faca
      EscrevaL (calista1, calista2)
    fimpara
  fimpara

// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo