Algoritmo "matrizIdentidade"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/12/2020
Var
mID: vetor [1..3 , 1..3]   de inteiro
i,j: inteiro

// Seção de Declarações das variáveis 


Inicio
    Para i <- 1 ate 3 faca
      para
      fimpara
    fimpara
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo