Algoritmo "TesteVetor"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/06/2020
Var
V: Vetor [1..6] de inteiro
c: Inteiro
// Seção de Declarações das variáveis 


Inicio
Para c <- 1 ate 6 faca
    Escreva ("Digite o ", c, "o. valor: ")
    Leia (v[c])
Fimpara

Para   c <- 1 ate 6 faca
 Escreva (v[c])
Fimpara
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo